# Generated by Django 5.0.6 on 2024-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0002_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
