# Generated by Django 5.0.6 on 2024-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0003_testimony_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
