# Generated by Django 5.0.6 on 2024-06-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
